name: Python package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Build Package
      run: |
        poetry build
    - name: Change poetry config
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - name: Publish Package
      run: |
        poetry publish